In [3]:
# Sorting an array
import numpy as np 
import random
a=np.random.randint(50,100,23)
print(a)
b=np.sort(a)
print(b)

[71 73 58 96 75 71 58 51 81 59 55 90 67 53 82 78 51 83 83 63 59 88 51]
[51 51 51 53 55 58 58 59 59 63 67 71 71 73 75 78 81 82 83 83 88 90 96]


In [4]:
# Sorting of 2D array
import numpy as np 
import random
a=np.random.randint(25,75,24).reshape(6,4)
b=np.sort(a,axis=0)
c=np.sort(a,axis=1)
print(a)
print(b)
print(c)

[[63 45 30 61]
 [58 68 64 44]
 [37 28 66 36]
 [30 47 71 53]
 [70 57 44 40]
 [42 33 48 35]]
[[30 28 30 35]
 [37 33 44 36]
 [42 45 48 40]
 [58 47 64 44]
 [63 57 66 53]
 [70 68 71 61]]
[[30 45 61 63]
 [44 58 64 68]
 [28 36 37 66]
 [30 47 53 71]
 [40 44 57 70]
 [33 35 42 48]]


In [5]:
# Using of np.append
# append means adding value at last position
import numpy as np 
import random
a=np.random.randint(25,75,36)
print(a)
b=np.append(a,300)
print(b)



[59 55 42 35 31 73 63 54 34 33 51 52 67 71 29 26 45 31 74 59 45 37 50 62
 65 61 71 28 26 53 32 60 45 36 63 29]
[ 59  55  42  35  31  73  63  54  34  33  51  52  67  71  29  26  45  31
  74  59  45  37  50  62  65  61  71  28  26  53  32  60  45  36  63  29
 300]


In [10]:
# Using of np.append in 2D array
import numpy as np 
import random
a=np.random.randint(25,75,24).reshape(6,4)
b=np.append(a,np.ones((a.shape[0],1)),axis=1)
print(a)
print(b)


[[62 28 30 71]
 [49 53 34 31]
 [61 35 56 25]
 [74 34 59 74]
 [40 72 70 68]
 [55 62 71 29]]
[[62. 28. 30. 71.  1.]
 [49. 53. 34. 31.  1.]
 [61. 35. 56. 25.  1.]
 [74. 34. 59. 74.  1.]
 [40. 72. 70. 68.  1.]
 [55. 62. 71. 29.  1.]]


In [14]:
# Concatenation of arrays using np.concatenate 
import numpy as np
import random
a=np.random.randint(1,29,4).reshape(2,2)
b=np.random.randint(1,36,4).reshape(2,2)
c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=1)
print(a)
print(b)
print(c)
print(d)

[[21  3]
 [19 19]]
[[30 13]
 [ 4  4]]
[[21  3]
 [19 19]
 [30 13]
 [ 4  4]]
[[21  3 30 13]
 [19 19  4  4]]


In [15]:
#concatenation of 2D arrays
import numpy as np
import random 
a=np.random.randint(0,50,24).reshape(6,4)
b=np.random.randint(0,50,24).reshape(6,4)
c=np.concatenate((a,b),axis=0)
d=np.concatenate((a,b),axis=1)
print(a)
print(b)
print(c)
print(d)

[[ 9 43 33  5]
 [ 7 17  9 42]
 [28 24 33 31]
 [46 49 15 39]
 [43 28 21 30]
 [41 11  6 22]]
[[19 32 42 15]
 [ 8 18 14 18]
 [27 27 41 38]
 [36  7 27 47]
 [25 41 47 49]
 [39 23 45 16]]
[[ 9 43 33  5]
 [ 7 17  9 42]
 [28 24 33 31]
 [46 49 15 39]
 [43 28 21 30]
 [41 11  6 22]
 [19 32 42 15]
 [ 8 18 14 18]
 [27 27 41 38]
 [36  7 27 47]
 [25 41 47 49]
 [39 23 45 16]]
[[ 9 43 33  5 19 32 42 15]
 [ 7 17  9 42  8 18 14 18]
 [28 24 33 31 27 27 41 38]
 [46 49 15 39 36  7 27 47]
 [43 28 21 30 25 41 47 49]
 [41 11  6 22 39 23 45 16]]


In [16]:
# getting unique values of the array 
import numpy as np 
import random 
a=np.random.randint(1,10,9)
b=np.unique(a)
print(a)
print(b)

[2 8 6 3 5 5 4 7 4]
[2 3 4 5 6 7 8]


In [18]:
# Expanding the dimensions of the arrays by using np.expand_dims
a=np.random.randint(25,56,7)
b=a.shape
c=np.expand_dims(a,axis=0)
d=c.shape
e=np.expand_dims(a,axis=1)
f=e.shape
print(a)
print("Shape of a is ",b)
print(c)
print("Shape of c is ",d)
print(e)
print("Shape of e is ",f)


[54 35 38 38 32 38 31]
Shape of a is  (7,)
[[54 35 38 38 32 38 31]]
Shape of c is  (1, 7)
[[54]
 [35]
 [38]
 [38]
 [32]
 [38]
 [31]]
Shape of e is  (7, 1)


In [22]:
# Using of np.where
a=np.random.randint(1,50,24)
b=np.where(a>25)
print(a)
print(b)

# replacing values 
c=np.where(a>40,0,a)
print(c)

[29 32 29 26 19 23  7 26 15 38  1 29 13 41 33 42 41 42 25  4  9 46  7 48]
(array([ 0,  1,  2,  3,  7,  9, 11, 13, 14, 15, 16, 17, 21, 23]),)
[29 32 29 26 19 23  7 26 15 38  1 29 13  0 33  0  0  0 25  4  9  0  7  0]


In [23]:
# Replacing the values 
import numpy as np
import random 
a=np.random.randint(50,100,36)
b=np.where((a>75)&(a%2==0),0,a)
print(a)
print(b)

[99 87 54 74 57 97 97 57 94 73 55 99 56 63 71 60 63 82 64 95 90 94 90 97
 52 93 85 91 64 66 94 58 96 77 64 51]
[99 87 54 74 57 97 97 57  0 73 55 99 56 63 71 60 63  0 64 95  0  0  0 97
 52 93 85 91 64 66  0 58  0 77 64 51]


In [24]:
# np.argmax use 
# It is used to get the indices of maximum elelement 
import numpy as np 
import random 
a=np.random.randint(5,65,40)
print(a)
b=np.argmax(a)
print(b)


[27 47 34 10 10 58 35 18 29 61 22 12 21 45 46 36 58 58  5 61 12 53 38 46
 21 42 23 61 55 48 37 36 55 46  8 61 53 49 28 12]
9


In [25]:
# np.argmax in 2D array 
import numpy as np 
import random
a=np.random.randint(0,50,24).reshape(6,4)
b=np.argmax(a,axis=0)
c=np.argmax(a,axis=1)
print(a)
print(b)
print(c)


[[13 44 42 17]
 [27 14  4 17]
 [19 22 19 19]
 [ 4 21  5  9]
 [33 21 43 37]
 [38 20  4 15]]
[5 0 4 4]
[1 0 1 1 2 0]


In [26]:
#np.argmin  
# It is used to get minimum value indice of the array 
import numpy as np 
import random 
a=np.random.randint(0,25,24)
print(a)
b=np.argmin(a)
print(b)

[14  2 11 15  3 18 20 24 18 10  4 19 13  9  6 11 12 17 14 12 13 18  1 18]
22


In [27]:
#np argmin in 2D array
import numpy as np 
import random 
a=np.random.randint(100,200,64).reshape(8,8)
print(a)
b=np.argmin(a,axis=1)
print(b)
c=np.argmin(a,axis=0)
print(c)

[[184 142 123 189 118 166 173 143]
 [147 161 151 158 193 186 104 155]
 [157 190 191 180 140 173 131 172]
 [130 159 146 178 178 193 103 104]
 [117 166 106 161 186 158 162 178]
 [137 187 159 108 110 153 185 174]
 [135 194 158 190 161 120 109 113]
 [179 116 121 195 183 180 167 153]]
[4 6 6 6 2 3 6 1]
[4 7 4 5 5 6 3 3]


In [29]:
# np.cumsum 
# It is used to find the cumulative sum of the array 
import numpy as np
import random
a=np.random.randint(10,99,25)
b=np.cumsum(a)
print(a)
print(b)

[47 93 84 63 44 18 35 54 86 32 57 37 60 13 89 10 10 49 52 19 36 35 72 64
 30]
[  47  140  224  287  331  349  384  438  524  556  613  650  710  723
  812  822  832  881  933  952  988 1023 1095 1159 1189]


In [32]:
# np.cumsum in 2D
import numpy as np 
import random 
a=np.random.randint(100,200,25).reshape(5,5)
b=np.cumsum(a,axis=0)
c=np.cumsum(a,axis=1)
d=np.cumsum(a)
print(a)
print(b)
print(c)
print(d)

[[170 132 182 177 159]
 [178 158 198 147 145]
 [124 178 143 176 174]
 [117 188 178 137 114]
 [196 117 134 189 187]]
[[170 132 182 177 159]
 [348 290 380 324 304]
 [472 468 523 500 478]
 [589 656 701 637 592]
 [785 773 835 826 779]]
[[170 302 484 661 820]
 [178 336 534 681 826]
 [124 302 445 621 795]
 [117 305 483 620 734]
 [196 313 447 636 823]]
[ 170  302  484  661  820  998 1156 1354 1501 1646 1770 1948 2091 2267
 2441 2558 2746 2924 3061 3175 3371 3488 3622 3811 3998]


In [33]:
# np.cumprod 
# np.cumprod is used to find the cumulative product in the array
a=np.random.randint(12,24,8)
print(a)
b=np.cumprod(a)
print(b)

[21 16 15 23 22 18 19 12]
[         21         336        5040      115920     2550240    45904320
   872182080 10466184960]


In [34]:
# np.cumprod in 2D
import numpy as np 
import random 
a=np.random.randint(1,50,24).reshape(6,4)
print(a)
b=np.cumprod(a,axis=0)
print(b)
c=np.cumprod(a,axis=1)
print(c)
d=np.cumprod(a)
print(d)

[[12 26 47 27]
 [18 24 32 41]
 [11 11  6 18]
 [ 2 45  6 22]
 [47 11  4 22]
 [ 2 19 18 48]]
[[       12        26        47        27]
 [      216       624      1504      1107]
 [     2376      6864      9024     19926]
 [     4752    308880     54144    438372]
 [   223344   3397680    216576   9644184]
 [   446688  64555920   3898368 462920832]]
[[    12    312  14664 395928]
 [    18    432  13824 566784]
 [    11    121    726  13068]
 [     2     90    540  11880]
 [    47    517   2068  45496]
 [     2     38    684  32832]]
[                  12                  312                14664
               395928              7126704            171040896
           5473308672         224405655552        2468462211072
       27153084321792      162918505930752     2932533106753536
     5865066213507072   263927979607818240  1583567877646909440
 -2054994839187095552 -4351037073245732864  7478824415425593344
 -6978190485716729856 -5946238096091643904  6554267881526263808
 -4596118766967

In [35]:
# np.percentile ->it is used in finding numbers on a given percentile 
import numpy as np 
import random 
a=np.random.randint(25,75,100)
print(a)
b=np.percentile(a,100)
print(b)

[27 46 64 50 41 33 45 36 30 64 44 26 40 74 36 49 42 45 38 25 66 59 67 38
 30 59 41 52 63 34 34 72 28 51 45 65 37 30 43 27 43 42 33 43 71 65 73 47
 67 38 44 40 39 67 64 39 43 70 59 38 56 26 42 27 70 60 48 27 74 62 70 46
 63 29 47 25 53 51 25 27 48 60 35 58 60 56 69 59 50 63 63 47 61 33 43 32
 73 66 30 28]
74.0


In [38]:
# np.histogram 
# helps to find frequency count in array respective to bin size
import numpy as np 
import random 
a=np.random.randint(1,100,100)
b=np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])
print(a)
print(np.sort(a))
print(b)

[ 9 73 50 38 10  4 80 24 23 94 11 51 23 37 14 76 13 25 77 88 67 76 14 53
 89 15 27 80 13 90 78 32 64 88 79 63 71 93 26 96 72 29 37  3 59 37 78 15
 25 80 17 85 35 77 69  5 26 13 68 96 72 92 44 45 77 98 99  8 27 79 17 71
  5 93 24 36 85 51 77 92 30  4 57 72 76  8 63 49 84  5 77  9 83 96 98 51
 85 51 36 58]
[ 3  4  4  5  5  5  8  8  9  9 10 11 13 13 13 14 14 15 15 17 17 23 23 24
 24 25 25 26 26 27 27 29 30 32 35 36 36 37 37 37 38 44 45 49 50 51 51 51
 51 53 57 58 59 63 63 64 67 68 69 71 71 72 72 72 73 76 76 76 77 77 77 77
 77 78 78 79 79 80 80 80 83 84 85 85 85 88 88 89 90 92 92 93 93 94 96 96
 96 98 98 99]
(array([10, 11, 11,  9,  3,  9,  6, 18, 11, 12]), array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))


In [39]:
# np.corrcoef -> Used to find the value of pearson coefficient or correlation coefficient 
import numpy as np 
import random
salary=np.array([20000,35000,40000,60000,77000])
expirience=np.array([1,2,2,3,5])
x=np.corrcoef(salary,expirience)
print(x)

[[1.        0.9742766]
 [0.9742766 1.       ]]


In [40]:
#np.isin -> use to check values are present in array or not 
import numpy as np 
import random 
a=np.random.randint(1,100,100)
items=[10,20,30,40,50,60,70,80,90,100]
b=np.isin(a,items)
print(a)
print(items)
print(b)

[39 44 55 80 22 73 72 38 17 37 69 41 50 72 58 46 31 61 17 64 99 13 22 57
 35 17 88 85 63 53 90 96 92 35 44 18 34 34  7 33 31 58 32 91 13  1 41 75
 40 20 70 81 70 19 71 16 44 37 60 83 24 46  8 17 66 65 46 50 23 66 57 23
 32 34 29 30 70 34 95 94 89 37 89 68 44 33 18 59 39 54 55 39 87 87 40 98
 60 51 46 46]
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
[False False False  True False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
  True  True  True False  True False False False False False  True False
 False False False False False False False  True False False False False
 False False False  True  True False False False False False False False
 False False False False False False False False False False  True False
  True False False False]


In [41]:
# np.flip -> use to flip the value of the array
import numpy as np
import random 
a=np.random.randint(56,425,15)
print(a)
b=np.flip(a)
print(b)

[360  84 168 157 187 360 289 376 290 139  74 357 267 379 138]
[138 379 267 357  74 139 290 376 289 360 187 157 168  84 360]


In [42]:
# flipping in a 2D array
import numpy as np
import random 
a=np.random.randint(100,185,36).reshape(6,6)
print(a)
b=np.flip(a,axis=0)
print(b)
c=np.flip(a,axis=1)
print(c)
d=np.flip(a)
print(d)

[[163 150 128 135 116 107]
 [101 129 122 130 109 178]
 [133 172 124 179 104 175]
 [106 115 178 115 104 168]
 [150 175 168 146 128 136]
 [163 125 112 145 155 142]]
[[163 125 112 145 155 142]
 [150 175 168 146 128 136]
 [106 115 178 115 104 168]
 [133 172 124 179 104 175]
 [101 129 122 130 109 178]
 [163 150 128 135 116 107]]
[[107 116 135 128 150 163]
 [178 109 130 122 129 101]
 [175 104 179 124 172 133]
 [168 104 115 178 115 106]
 [136 128 146 168 175 150]
 [142 155 145 112 125 163]]
[[142 155 145 112 125 163]
 [136 128 146 168 175 150]
 [168 104 115 178 115 106]
 [175 104 179 124 172 133]
 [178 109 130 122 129 101]
 [107 116 135 128 150 163]]


In [47]:
# np.put() -> this function is used to insert a value in the array on a given index
import numpy as np 
import random 
a=np.random.randint(101,150,25).reshape(5,5)
print(a)
np.put(a,[2,5],[225,635])
print(a)

[[139 146 130 136 128]
 [112 130 118 142 140]
 [116 120 138 126 110]
 [114 131 111 123 104]
 [119 112 137 146 112]]
[[139 146 225 136 128]
 [635 130 118 142 140]
 [116 120 138 126 110]
 [114 131 111 123 104]
 [119 112 137 146 112]]


In [49]:
# np.delete ->used to delete an element from the array 
import numpy as np 
import random
a=np.random.randint(0,100,10)
print(a)
b=np.delete(a,[0,2,5])
print(b)


[14 73 61 24 48 64 31 49  5  2]
[73 24 48 31 49  5  2]


In [50]:
#np.delete -> used to delete in 2D array 
import numpy as np 
import random 
a=np.random.randint(25,75,24).reshape(6,4)
print(a)
b=np.delete(a,1,axis=0)
print(b)
c=np.delete(a,3,axis=1)
print(c)

[[41 65 67 59]
 [29 36 62 39]
 [28 26 43 34]
 [66 36 61 62]
 [31 46 67 50]
 [68 50 37 43]]
[[41 65 67 59]
 [28 26 43 34]
 [66 36 61 62]
 [31 46 67 50]
 [68 50 37 43]]
[[41 65 67]
 [29 36 62]
 [28 26 43]
 [66 36 61]
 [31 46 67]
 [68 50 37]]


In [57]:
# Set functions or operations
import numpy as np
import random 

a=np.random.randint(1,5,4)
b=np.random.randint(3,8,4)
c=np.sort(a)
d=np.sort(b)
print(a)
print(b)
print(c)
print(d)

#np.union1d
e=np.union1d(c,d)
print("Union ",e)

#np.intersect1d
f=np.intersect1d(c,d)
print("intersection",f)

#np.setdifference1d
g=np.setdiff1d(c,d)
print("set difference ",g)

#np.setexor1d
h=np.setxor1d(c,d)
print("Exor ",h)

#np.isin
i=np.isin(c,5)
print(i)


[3 4 4 3]
[4 7 7 3]
[3 3 4 4]
[3 4 7 7]
Union  [3 4 7]
intersection [3 4]
set difference  []
Exor  [7]
[False False False False]


In [58]:
# np.clip -> use to clip to limit the values in the array
import numpy as np 
import random 
a=np.random.randint(100,200,50)
b=np.clip(a,a_min=125,a_max=175)
print(a)
print(b)

[106 112 189 117 199 121 191 173 152 117 126 136 115 188 177 149 134 149
 159 119 193 186 153 151 159 185 192 110 168 174 142 122 154 158 102 189
 145 164 108 180 163 144 142 102 140 139 119 122 116 100]
[125 125 175 125 175 125 175 173 152 125 126 136 125 175 175 149 134 149
 159 125 175 175 153 151 159 175 175 125 168 174 142 125 154 158 125 175
 145 164 125 175 163 144 142 125 140 139 125 125 125 125]
