In [5]:
# Numpy arrays
#1D arrays
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [6]:
# 2D arrays
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
print(type(a))


[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [7]:
# 3D arrays
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(type(a))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [8]:
# Change datatype of an array 
import numpy as np 
a=np.array([1,2,3],dtype=float)
print(a)
print(type(a))
b=np.array([1,2,3],dtype=bool)
print(b)
print(type(b))
c=np.array([1,2,3],dtype=complex)
print(c)
print(type(c))


[1. 2. 3.]
<class 'numpy.ndarray'>
[ True  True  True]
<class 'numpy.ndarray'>
[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.ndarray'>


In [9]:
# Creating arrays using np.arange
a=np.arange(1,11)
b=np.arange(1,11,2)
print(a)
print(type(a))
print(b)
print(type(b))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[1 3 5 7 9]
<class 'numpy.ndarray'>


In [12]:
# Reshape arrays whoch are maked by np.arange
a=np.arange(1,11).reshape(2,5)
print(a)
print(type(a))
b=np.arange(0,12).reshape(4,3)
print(b)
print(type(b))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>


In [14]:
# np.ones and np.zeros
a=np.ones((3,4))
print(a)
print(type(a))
b=np.zeros((2,8))
print(b)
print(type(b))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [15]:
# Random value in arrays
a=np.random.random((3,4))
print(a)
print(type(a))

[[0.81692273 0.0877637  0.29027686 0.14954372]
 [0.90111204 0.25988813 0.69817945 0.81755464]
 [0.82462296 0.70720383 0.24887363 0.11533338]]
<class 'numpy.ndarray'>


In [16]:
# Create linear points on equal distance linearly
a=np.linspace(-10,10,10)
print(a)
print(type(a))


[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]
<class 'numpy.ndarray'>


In [17]:
# creating an identity matrix
a=np.identity(3)
print(a)
print(type(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.ndarray'>


In [18]:
# ndim dimensions of array
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)


3
2
1


In [19]:
#shape tells the shape of array
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1.shape)
print(a2.shape)
print(a3.shape)



(10,)
(3, 4)
(2, 2, 2)


In [20]:
# Tells size of the array
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1.size)
print(a2.size)
print(a3.size)


10
12
8


In [23]:
# itemsize tells the size of the datatype in item
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)


8
8
8


In [24]:
#dtype , tells datatype of the item
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)


int64
float64
int64


In [25]:
# Changing datatype
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a3.astype(np.int32))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [26]:
#scalar operations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1+2)
print(a1-2)
print(a1*2)
print(a1/2)
print(a1**2)
print(a1%2)
print(a2+2)
print(a2-2)
print(a2*2)
print(a2/2)
print(a2**2)
print(a2%2)


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]
[[14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
[[ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]
[[144 169 196 225]
 [256 289 324 361]
 [400 441 484 529]]
[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [27]:
#vector operations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)
print(a1%a2)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]
[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]
[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]
[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [29]:
#Array functions
a1=np.random.random((3,3))
a2=np.round(a1*100)
#sum of elements
print(np.sum(a2))
#product of elements
print(np.prod(a2))
#maximum of element
print(np.max(a2))
#minimum of elements
print(np.min(a2))
#mean of elements
print(np.mean(a2))
#median of elements
print(np.median(a2))
#variance of elements
print(np.var(a2))
#standard deviation of elements
print(np.std(a2))


463.0
554874486566400.0
92.0
13.0
51.44444444444444
38.0
739.5802469135803
27.195224707907457


In [31]:
#Array functions rowwise
a1=np.random.random((3,3))
a2=np.round(a1*100)
#sum of elements
print(np.sum(a2,axis=1))
#product of elements
print(np.prod(a2,axis=1))
#maximum of element
print(np.max(a2,axis=1))
#minimum of elements
print(np.min(a2,axis=1))
#mean of elements
print(np.mean(a2,axis=1))
#median of elements
print(np.median(a2,axis=1))
#variance of elements
print(np.var(a2,axis=1))
#standard deviation of elements
print(np.std(a2,axis=1))


[222.  47. 172.]
[382674.   1728.  33810.]
[94. 27. 98.]
[59.  4.  5.]
[74.         15.66666667 57.33333333]
[69. 16. 69.]
[ 216.66666667   88.22222222 1509.55555556]
[14.71960144  9.39266854 38.85299931]


In [32]:
#Array functions columnwise
a1=np.random.random((3,3))
a2=np.round(a1*100)
#sum of elements
print(np.sum(a2,axis=0))
#product of elements
print(np.prod(a2,axis=0))
#maximum of element
print(np.max(a2,axis=0))
#minimum of elements
print(np.min(a2,axis=0))
#mean of elements
print(np.mean(a2,axis=0))
#median of elements
print(np.median(a2,axis=0))
#variance of elements
print(np.var(a2,axis=0))
#standard deviation of elements
print(np.std(a2,axis=0))


[159.  78.  80.]
[93177. 14352. 16000.]
[87. 39. 40.]
[21. 16. 20.]
[53.         26.         26.66666667]
[51. 23. 20.]
[728.          92.66666667  88.88888889]
[26.98147513  9.62635272  9.42809042]


In [35]:
#Trigonometric functions
a1=np.random.random((3,3))
a2=np.round(a1*100)
print(np.sin(a2))
print(np.cos(a2))
print(np.tan(a2))

[[ 0.10598751  0.         -0.85551998]
 [ 0.98358775 -0.77946607  0.98935825]
 [-0.75098725  0.73319032  0.0353983 ]]
[[-0.99436746  1.         -0.5177698 ]
 [-0.18043045 -0.62644445 -0.14550003]
 [ 0.66031671 -0.6800235   0.99937328]]
[[-0.10658787  0.          1.65231726]
 [-5.45134011  1.24427006 -6.79971146]
 [-1.13731371 -1.07818381  0.0354205 ]]


In [40]:
# Dot product 
a1=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
print(np.dot(a1,a3))


[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [42]:
#Logarithms and exponents
a1=np.arange(1,13).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
print(np.log(a1))
print(np.log(a3))
print(np.exp(a1))
print(np.exp(a3))

[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]
[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


In [43]:
#Round floor and ceil 
a1=(np.random.random((2,3))*100)
print(np.round(a1))
print(np.floor(a1))
print(np.ceil(a1))

[[70. 96. 32.]
 [20. 23. 44.]]
[[69. 96. 31.]
 [19. 23. 43.]]
[[70. 97. 32.]
 [20. 24. 44.]]


In [3]:
#Indexing and slicing 
import numpy as np
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1[1])
print(a3[1,0,1])
print(a3[1,1,0])
print(a1[2:5])
print(a2[0,:])
print(a2[:,2])
print(a2[::2,::3])
print(a2[::2,1::2])
print(a2[1,::3])
print(a2[0:2,1:])
a4=np.arange(27).reshape(3,3,3)
print(a4[2,1:,1:])
print(a4[0::2,0,0::2])

1
5
6
[2 3 4]
[0 1 2 3]
[ 2  6 10]
[[ 0  3]
 [ 8 11]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]
[[22 23]
 [25 26]]
[[ 0  2]
 [18 20]]


In [10]:
#Iterating
import numpy as np
a3=np.arange(8).reshape(2,2,2)
for i in np.nditer(a3):
    print(i)

a4=np.random.random((6,5))
a5=np.round(a4*100)
for j in np.nditer(a5):
    print(j)

0
1
2
3
4
5
6
7
48.0
64.0
40.0
61.0
33.0
52.0
20.0
72.0
49.0
60.0
47.0
56.0
42.0
70.0
79.0
92.0
91.0
55.0
86.0
45.0
88.0
90.0
80.0
90.0
53.0
82.0
75.0
44.0
12.0
95.0


In [13]:
#Transpose of a matrix
import numpy as np
a1=np.random.random((4,6))
a2=np.round(100*a1)
print(a2)
a3=np.transpose(a2)
print(a3)

[[68.  8.  3. 75. 85. 34.]
 [13. 32. 64. 22. 25. 46.]
 [15. 51. 73.  0. 10. 99.]
 [13. 18. 80.  4. 55. 22.]]
[[68. 13. 15. 13.]
 [ 8. 32. 51. 18.]
 [ 3. 64. 73. 80.]
 [75. 22.  0.  4.]
 [85. 25. 10. 55.]
 [34. 46. 99. 22.]]


In [14]:
# Ravel- Convert X-d array into 1D array
a1=np.arange(12).reshape(2,3,2)
print(a1)
print(a1.ravel())

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
#horizontal stacking -> adding of arrays horizontally
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a3=np.hstack((a1,a2))
print(a1)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [17]:
#vertical stacking ->adding of arrays vertically
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a3=np.vstack((a1,a2))
print(a1)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
#horizontal splitting
a1=np.random.random((6,4))
a2=np.round(a1*100)
print(a2)
a3=np.hsplit(a2,2)
print(a3)

[[61. 44. 65.  2.]
 [36. 38. 41. 64.]
 [ 6. 39. 92. 96.]
 [91. 65. 61. 61.]
 [34. 63. 36. 10.]
 [85. 95.  2. 14.]]
[array([[61., 44.],
       [36., 38.],
       [ 6., 39.],
       [91., 65.],
       [34., 63.],
       [85., 95.]]), array([[65.,  2.],
       [41., 64.],
       [92., 96.],
       [61., 61.],
       [36., 10.],
       [ 2., 14.]])]


In [21]:
#Vertical splitting
a1=np.random.random((6,4))
a2=np.round(a1*100)
print(a2)
a3=np.vsplit(a2,3)
print(a3)

[[40. 80. 24. 31.]
 [46. 24. 62. 46.]
 [47. 13. 48. 47.]
 [83. 42. 33. 61.]
 [58. 95. 99. 77.]
 [81. 80. 99. 37.]]
[array([[40., 80., 24., 31.],
       [46., 24., 62., 46.]]), array([[47., 13., 48., 47.],
       [83., 42., 33., 61.]]), array([[58., 95., 99., 77.],
       [81., 80., 99., 37.]])]
